import type { ClientProject } from "@/lib/client-projects";
import type { ProjectComment } from "@/components/project-comments";

/**
 * Four made-up projects (one per stage) so the Your Projects page can be tried without any data: open
 * /en/my-projects?sample=1 while signed in. The films are the site's own showreel clips on Bunny. Real projects come
 * from the Supabase `projects` table (supabase/projects.sql).
 */
export const SAMPLE_PROJECTS: ClientProject[] = [
  {
    id: "sample-1",
    title: "Summer Sale Reel",
    kind: "Social Media Ad",
    status: "delivered",
    brief: "A 15-second vertical ad for our summer sale. Bright, fast, product first, with our logo in the last two seconds. Voiceover in English.",
    thumbnailUrl: null,
    videoId: "b7bd4d28-a15f-46cc-a82e-800d9d4e3ee9",
    durationSeconds: 15,
    dueDate: "2026-10-05",
    revisionsTotal: 2,
    revisionsUsed: 1,
    createdAt: "2026-09-22T09:00:00Z",
    timeline: [
      { title: "Brief received", date: "2026-09-22", note: "We confirmed the goal, the audience and the format.", done: true },
      { title: "Script approved", date: "2026-09-24", note: "Three hooks proposed; you picked the second.", done: true },
      { title: "First cut delivered", date: "2026-09-30", note: null, done: true },
      { title: "Revision: bigger logo at the end", date: "2026-10-02", note: "Done in one day.", done: true },
      { title: "Final files delivered", date: "2026-10-05", note: "9:16, 1:1 and 16:9 exports.", done: true },
    ],
    format: "9:16 vertical",
    managerName: "Nikolay from Keplerbay",
    nextStep: "All done - your final files are ready to download.",
    briefAnswers: [
      { label: "Goal", value: "Boost summer sale sales" },
      { label: "Audience", value: "Women 25-40, Bulgaria" },
      { label: "Style", value: "Bright, fast, product first" },
      { label: "Voiceover", value: "English, female" },
      { label: "Where it runs", value: "Instagram Reels, TikTok" },
    ],
    files: [
      { name: "Summer-Sale-9x16.mp4", url: "#", path: null, size: "18 MB" },
      { name: "Summer-Sale-1x1.mp4", url: "#", path: null, size: "16 MB" },
      { name: "Summer-Sale-16x9.mp4", url: "#", path: null, size: "21 MB" },
    ],
    deliveryVideo: null,
    approvedAt: null,
    revisionHistory: [{ title: "Bigger logo at the end", date: "2026-10-02", done: true }],
    commentCount: 2,
    awaitingReply: false,
    userId: "sample-user",
    clientName: "Maria Ivanova",
    clientEmail: "maria@bloomcosmetics.example",
    briefFiles: [{ name: "summer-sale-script.pdf", path: "sample/summer-sale-script.pdf", size: 412000 }, { name: "logo.png", path: "sample/logo.png", size: 88000 }],
  },
  {
    id: "sample-2",
    title: "Titanium Wok Launch",
    kind: "TV Ad",
    status: "review",
    brief: "A 30-second commercial for a new titanium wok: steam, sizzle, close-ups of the food. Premium and warm. Broadcast-ready audio.",
    thumbnailUrl: null,
    videoId: "5b06ab4b-b780-4e11-96fe-571b71dfa9aa",
    durationSeconds: 30,
    dueDate: "2026-10-14",
    revisionsTotal: 2,
    revisionsUsed: 0,
    createdAt: "2026-09-26T09:00:00Z",
    timeline: null,
    format: "16:9 broadcast",
    managerName: "Nikolay from Keplerbay",
    nextStep: "Watch the cut and send your notes - you have 2 revisions included.",
    briefAnswers: [
      { label: "Goal", value: "Launch the titanium wok on TV" },
      { label: "Audience", value: "Home cooks 30-55" },
      { label: "Style", value: "Premium, warm, cinematic" },
      { label: "Audio", value: "Broadcast-ready, no voiceover" },
    ],
    files: [],
    deliveryVideo: null,
    approvedAt: null,
    revisionHistory: [],
    userId: "sample-user",
    clientName: "Georgi Petrov",
    clientEmail: "georgi@titanwok.example",
    briefFiles: [{ name: "product-photos.zip", path: "sample/product-photos.zip", size: 3100000 }],
  },
  {
    id: "sample-3",
    title: "Brand Story Film",
    kind: "Corporate Video",
    status: "production",
    brief: "A one-minute film about who we are and why clients trust us, for our website and investor meetings. Calm, confident, no stock-footage feel.",
    thumbnailUrl: null,
    videoId: null,
    durationSeconds: 60,
    dueDate: "2026-10-30",
    revisionsTotal: 3,
    revisionsUsed: 0,
    createdAt: "2026-09-28T09:00:00Z",
    timeline: [
      { title: "Brief received", date: "2026-09-28", note: null, done: true },
      { title: "Script and storyboard approved", date: "2026-10-03", note: "Fourteen shots, one voiceover.", done: true },
      { title: "Scenes in production", date: null, note: "We are generating and directing the shots now.", done: false },
      { title: "Voiceover, music and subtitles", date: null, note: null, done: false },
      { title: "Review and delivery", date: "2026-10-30", note: null, done: false },
    ],
    format: "16:9",
    managerName: "Nikolay from Keplerbay",
    nextStep: "We are producing the scenes. Nothing needed from you right now.",
    briefAnswers: [
      { label: "Goal", value: "Tell our story to investors" },
      { label: "Audience", value: "Investors and partners" },
      { label: "Tone", value: "Calm, confident" },
      { label: "Language", value: "English with Bulgarian subtitles" },
    ],
    files: [],
    deliveryVideo: null,
    approvedAt: null,
    revisionHistory: [],
    commentCount: 2,
    awaitingReply: true,
    userId: "sample-user",
    clientName: "Elena Dimitrova",
    clientEmail: "elena@northbridge.example",
    briefFiles: [{ name: "company-overview.pdf", path: "sample/company-overview.pdf", size: 1200000 }, { name: "brand-guidelines.pdf", path: "sample/brand-guidelines.pdf", size: 2400000 }],
  },
  {
    id: "sample-4",
    title: "Product Teaser",
    kind: "Product Video",
    status: "scripting",
    brief: null,
    thumbnailUrl: null,
    videoId: null,
    durationSeconds: 20,
    dueDate: "2026-11-08",
    revisionsTotal: 2,
    revisionsUsed: 0,
    createdAt: "2026-10-01T09:00:00Z",
    timeline: null,
    format: "1:1 square",
    managerName: "Nikolay from Keplerbay",
    nextStep: "We are writing the script. You will get it to approve in 2 days.",
    briefAnswers: [
      { label: "Product", value: "Wireless earbuds" },
      { label: "Style", value: "Clean, tech, dark background" },
    ],
    files: [],
    deliveryVideo: null,
    approvedAt: null,
    revisionHistory: [],
    userId: "sample-user",
    clientName: "Ivan Todorov",
    clientEmail: "ivan@soundwave.example",
    briefFiles: [],
  },
];

/** Made-up comment threads for the sample projects (sample mode only). */
export const SAMPLE_COMMENTS: Record<string, ProjectComment[]> = {
  "sample-1": [
    { id: "c1", authorName: "Maria Ivanova", isTeam: false, body: "Could the logo at the end be a little bigger? Otherwise it's perfect.", createdAt: "2026-10-01T10:12:00Z" },
    { id: "c2", authorName: "Nikolay", isTeam: true, body: "Done - new version is in your files. The logo now holds for the last 2.5 seconds.", createdAt: "2026-10-02T09:40:00Z" },
  ],
  "sample-3": [
    { id: "c3", authorName: "Nikolay", isTeam: true, body: "Storyboard approved, thank you. We are generating the scenes now. Do you want the voiceover male or female?", createdAt: "2026-10-03T14:05:00Z" },
    { id: "c4", authorName: "Elena Dimitrova", isTeam: false, body: "Female, calm, please.", createdAt: "2026-10-03T15:30:00Z" },
  ],
};
