import type { Metadata } from "next";
import { Exo_2, Montserrat, Nunito, Playfair_Display, Unbounded } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { SmoothScroll } from "@/components/smooth-scroll";
import { LanguageProvider } from "@/lib/i18n/language-context";
import { SOCIAL_LINKS } from "@/lib/social-links";
import { Analytics } from "@vercel/analytics/next";
import { PostHogProvider } from "@/components/posthog-provider";
import { PostHogPageView } from "@/components/posthog-pageview";
import { Suspense } from "react";
import Script from "next/script";

/**
 * Fonts are self-hosted by `next/font` (no runtime request to Google), so they
 * can't fail to load behind a CSS `@import`. Cyrillic subsets are required —
 * the site is Bulgarian-first. Exo 2 (headings and body alike) is variable
 * (100–900), so no `weight`; the display faces that ship static files list
 * the weights they are used at.
 */

/**
 * The projects showcase's display faces - one per brand world (`showcase-scenes.tsx`, `headline`), all with
 * Cyrillic: Montserrat (the giant "Boleron" word, the face the reference animation uses, and Boleron's corporate
 * headline), Playfair Display (Emblema, as in the reference), Exo 2 (Plasico's tech), Nunito (OSMO's home-friendly
 * rounded), Unbounded (MindGuard's big, strong one).
 */
const montserrat = Montserrat({
  subsets: ["latin", "cyrillic"],
  weight: ["700", "800"],
  variable: "--font-montserrat",
  display: "swap",
});
const playfair = Playfair_Display({
  subsets: ["latin", "cyrillic"],
  weight: ["500", "600"],
  style: ["normal", "italic"],
  variable: "--font-playfair",
  display: "swap",
});
/**
 * Exo 2 - the site's one face: headings (`font-heading`) and body / UI (`font-sans`) alike, and Plasico's showcase
 * headline. A variable font (100–900 + italic), so no weight list; `globals.css` maps both tokens to it.
 */
const exo = Exo_2({
  subsets: ["latin", "latin-ext", "cyrillic"],
  style: ["normal", "italic"],
  variable: "--font-exo",
  display: "swap",
});
const nunito = Nunito({
  subsets: ["latin", "cyrillic"],
  weight: ["800"],
  variable: "--font-nunito",
  display: "swap",
});
const unbounded = Unbounded({
  subsets: ["latin", "cyrillic"],
  weight: ["700"],
  variable: "--font-unbounded",
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL("https://dreamteam.video"),
  title: "DreamTeam | AI Video Production",
  description: "DreamTeam creates high-impact AI-generated videos for brands worldwide — from realistic to animated. Custom scripts, global clients, fast turnarounds.",
  keywords: [
    // English
    "AI video production",
    "AI video company",
    "AI-generated video",
    "video ads",
    "product videos",
    "brand mascots",
    "AI avatars",
    "explainer videos",
    "social media video",
    "TikTok video",
    "Instagram Reels",
    "corporate video",
    "DreamTeam",
    // Bulgarian
    "AI видео продукция",
    "рекламни видеа с изкуствен интелект",
    "видео реклами за бизнес",
    "продуктови видеа",
    "корпоративно видео",
    "AI аватари",
    "генериране на видео с изкуствен интелект",
    "видео за социални мрежи",
  ],
  alternates: {
    canonical: "/bg",
    languages: {
      en: "/en",
      bg: "/bg",
    },
  },
  openGraph: {
    title: "DreamTeam | AI Video Production",
    description: "End-to-end AI video production — photorealistic, animated, or hybrid. Serving global clients with custom scripts and diverse budgets.",
    type: "website",
    siteName: "DreamTeam",
    url: "https://dreamteam.video",
    locale: "bg_BG",
    alternateLocale: ["en_US"],
    // Social image is generated by src/app/opengraph-image.tsx.
  },
  twitter: {
    card: "summary_large_image",
    title: "DreamTeam",
    description: "AI-powered video production for modern brands.",
  },
  icons: {
    icon: "/logo/logo_short_black.png",
  },
};

// Organization + website structured data, so search engines and AI answer
// engines can identify DreamTeam as the business behind the site.
const STRUCTURED_DATA = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "ProfessionalService",
      "@id": "https://dreamteam.video/#organization",
      name: "DreamTeam",
      alternateName: "DreamTeam AI Video Production",
      url: "https://dreamteam.video",
      logo: "https://dreamteam.video/logo/logo_short_black.png",
      image: "https://dreamteam.video/opengraph-image",
      description:
        "AI video production company creating AI-generated video for brands — TV and social ads, product videos, brand mascots, explainer videos, and AI avatars. Serving Bulgaria and worldwide.",
      email: "info@dreamteam.technology",
      sameAs: SOCIAL_LINKS.map((s) => s.href),
      knowsLanguage: ["bg", "en"],
      areaServed: [{ "@type": "Country", name: "Bulgaria" }, "Worldwide"],
      address: {
        "@type": "PostalAddress",
        addressLocality: "Sofia",
        addressCountry: "BG",
      },
      serviceType: [
        "AI video production",
        "AI advertising video",
        "Product videos",
        "Brand mascots",
        "AI avatars",
        "Explainer videos",
      ],
      hasOfferCatalog: {
        "@type": "OfferCatalog",
        name: "AI Video Services",
        itemListElement: [
          {
            "@type": "Offer",
            itemOffered: {
              "@type": "Service",
              name: "AI Video Production",
              description:
                "AI videos for TV ads, social media campaigns, tutorials, product videos, and AI-avatar stories.",
            },
          },
          {
            "@type": "Offer",
            itemOffered: {
              "@type": "Service",
              name: "AI Brand Mascots",
              description: "Animated AI mascot characters for brands.",
            },
          },
          {
            "@type": "Offer",
            itemOffered: {
              "@type": "Service",
              name: "AI Images",
              description: "AI-generated stills and visuals for campaigns.",
            },
          },
          {
            "@type": "Offer",
            itemOffered: {
              "@type": "Service",
              name: "AI Automation",
              description: "Automated content and production pipelines.",
            },
          },
        ],
      },
    },
    {
      "@type": "WebSite",
      "@id": "https://dreamteam.video/#website",
      url: "https://dreamteam.video",
      name: "DreamTeam",
      inLanguage: ["bg", "en"],
      publisher: { "@id": "https://dreamteam.video/#organization" },
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Default to the primary locale (bg); LanguageProvider syncs the real
    // per-route language client-side. suppressHydrationWarning covers that swap.
    // `class="dark"` is rendered server-side so the FIRST paint is already dark —
    // without it the light `:root` palette flashes until next-themes' script runs.
    // next-themes reconciles this client-side if the visitor picked light.
    // Font variables live on <html>: `--font-sans` / `--font-heading` are
    // resolved on `:root`, so the families must be defined there too.
    <html
      lang="bg"
      className={`dark ${exo.variable} ${montserrat.variable} ${playfair.variable} ${nunito.variable} ${unbounded.variable}`}
      style={{ colorScheme: "dark" }}
      suppressHydrationWarning
    >
      <body className="font-sans antialiased relative min-h-screen" suppressHydrationWarning>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(STRUCTURED_DATA) }}
        />
        {/*
          OpenAI conversion pixel (oaiq). Vendor snippet kept verbatim: it stubs
          `window.oaiq` with a command queue, then injects the real SDK, so calls
          fired before the SDK lands are replayed. `afterInteractive` matches the
          vendor's plain <script> placement without blocking hydration.
        */}
        <Script id="openai-pixel" strategy="afterInteractive">
          {`!function(w,d,s,u){if(w.oaiq)return;var q=function(){q.q.push(arguments)};q.q=[];w.oaiq=q;var j=d.createElement(s);j.async=1;j.src=u;var f=d.getElementsByTagName(s)[0];f.parentNode.insertBefore(j,f)}(window,document,"script","https://bzrcdn.openai.com/sdk/oaiq.min.js");oaiq("init",{pixelId:"9vxEQCFdaKzy9yXADo8cMC",debug:true});`}
        </Script>
        <PostHogProvider>
          <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem={false}
              disableTransitionOnChange={false}
            >
              <LanguageProvider>
                <SmoothScroll />
                <Suspense fallback={null}>
                  <PostHogPageView />
                </Suspense>
                <div className="relative z-10">
                  {children}
                </div>
              </LanguageProvider>
            </ThemeProvider>
          <Analytics />
        </PostHogProvider>
      </body>
    </html>
  );
}
