import type { Metadata } from "next";
import { Syne } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { StyledComponentsRegistry } from "@/lib/styled-components-registry";
import { LanguageProvider } from "@/lib/i18n/language-context";
// import { FloatingAiAssistant } from "@/components/ui/glowing-ai-chat-assistant";
import { Analytics } from "@vercel/analytics/next";
import { PostHogProvider } from "@/components/posthog-provider";
import { PostHogPageView } from "@/components/posthog-pageview";
import { Suspense } from "react";

const syne = Syne({ 
  subsets: ["latin"],
  variable: "--font-syne",
});

export const metadata: Metadata = {
  metadataBase: new URL("https://dreamteam.video"),
  title: "DreamTeam | AI Video Production",
  description: "DreamTeam creates high-impact AI-generated videos for brands worldwide — from realistic to animated. Custom scripts, global clients, fast turnarounds.",
  keywords: [
    // English
    "AI video production",
    "AI video company",
    "AI-generated video",
    "video ads",
    "product videos",
    "brand mascots",
    "AI avatars",
    "explainer videos",
    "social media video",
    "TikTok video",
    "Instagram Reels",
    "corporate video",
    "DreamTeam",
    // Bulgarian
    "AI видео продукция",
    "рекламни видеа с изкуствен интелект",
    "видео реклами за бизнес",
    "продуктови видеа",
    "корпоративно видео",
    "AI аватари",
    "генериране на видео с изкуствен интелект",
    "видео за социални мрежи",
  ],
  alternates: {
    canonical: "/bg",
    languages: {
      en: "/en",
      bg: "/bg",
    },
  },
  openGraph: {
    title: "DreamTeam | AI Video Production",
    description: "End-to-end AI video production — photorealistic, animated, or hybrid. Serving global clients with custom scripts and diverse budgets.",
    type: "website",
    siteName: "DreamTeam",
    url: "https://dreamteam.video",
    locale: "bg_BG",
    alternateLocale: ["en_US"],
    // Social image is generated by src/app/opengraph-image.tsx.
  },
  twitter: {
    card: "summary_large_image",
    title: "DreamTeam",
    description: "AI-powered video production for modern brands.",
  },
  icons: {
    icon: "/logo/logo_short_black.png",
  },
};

// Organization + website structured data, so search engines and AI answer
// engines can identify DreamTeam as the business behind the site.
const STRUCTURED_DATA = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "ProfessionalService",
      "@id": "https://dreamteam.video/#organization",
      name: "DreamTeam",
      alternateName: "DreamTeam AI Video Production",
      url: "https://dreamteam.video",
      logo: "https://dreamteam.video/logo/logo_short_black.png",
      image: "https://dreamteam.video/opengraph-image",
      description:
        "AI video production company creating AI-generated video for brands — TV and social ads, product videos, brand mascots, explainer videos, and AI avatars. Serving Bulgaria and worldwide.",
      email: "info@dreamteam.technology",
      knowsLanguage: ["bg", "en"],
      areaServed: [{ "@type": "Country", name: "Bulgaria" }, "Worldwide"],
      address: {
        "@type": "PostalAddress",
        addressLocality: "Sofia",
        addressCountry: "BG",
      },
      serviceType: [
        "AI video production",
        "AI advertising video",
        "Product videos",
        "Brand mascots",
        "AI avatars",
        "Explainer videos",
      ],
      hasOfferCatalog: {
        "@type": "OfferCatalog",
        name: "AI Video Services",
        itemListElement: [
          {
            "@type": "Offer",
            itemOffered: {
              "@type": "Service",
              name: "AI Video Production",
              description:
                "AI videos for TV ads, social media campaigns, tutorials, product videos, and AI-avatar stories.",
            },
          },
          {
            "@type": "Offer",
            itemOffered: {
              "@type": "Service",
              name: "AI Brand Mascots",
              description: "Animated AI mascot characters for brands.",
            },
          },
          {
            "@type": "Offer",
            itemOffered: {
              "@type": "Service",
              name: "AI Images",
              description: "AI-generated stills and visuals for campaigns.",
            },
          },
          {
            "@type": "Offer",
            itemOffered: {
              "@type": "Service",
              name: "AI Automation",
              description: "Automated content and production pipelines.",
            },
          },
        ],
      },
    },
    {
      "@type": "WebSite",
      "@id": "https://dreamteam.video/#website",
      url: "https://dreamteam.video",
      name: "DreamTeam",
      inLanguage: ["bg", "en"],
      publisher: { "@id": "https://dreamteam.video/#organization" },
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Default to the primary locale (bg); LanguageProvider syncs the real
    // per-route language client-side. suppressHydrationWarning covers that swap.
    <html lang="bg" suppressHydrationWarning>
      <body
        className={`${syne.variable} font-sans antialiased relative min-h-screen`}
        suppressHydrationWarning
      >
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(STRUCTURED_DATA) }}
        />
        <PostHogProvider>
          <StyledComponentsRegistry>
            <ThemeProvider
              attribute="class"
              defaultTheme="light"
              enableSystem={false}
              disableTransitionOnChange={false}
            >
              <LanguageProvider>
                <Suspense fallback={null}>
                  <PostHogPageView />
                </Suspense>
                <div className="relative z-10">
                  {children}
                  {/* <FloatingAiAssistant /> */}
                </div>
              </LanguageProvider>
            </ThemeProvider>
          </StyledComponentsRegistry>
          <Analytics />
        </PostHogProvider>
      </body>
    </html>
  );
}
